package visao;
import biblioteca.Biblioteca;
import biblioteca.GerarCopiaArquivo;
import biblioteca.GetIPServidor;
import biblioteca.MetodosPublicos;
import static biblioteca.VariaveisPublicas.alterouBanco;
import static biblioteca.VariaveisPublicas.confIni;
import static biblioteca.VariaveisPublicas.ipServidor;
import static biblioteca.VariaveisPublicas.visualizandoInativos;
import static biblioteca.VariaveisPublicas.nivelAcessoUsuario;
import static biblioteca.VariaveisPublicas.tabela;
import conexao.ConnConexao;
import static biblioteca.VariaveisPublicas.nomeBancoSetado;
import javax.swing.JOptionPane;
import static biblioteca.VariaveisPublicas.status;
import static biblioteca.VariaveisPublicas.nomeUsuario;
import static biblioteca.VariaveisPublicas.rfUsuario;
import controle.ControleGravarLog;
import java.awt.Font;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import modelo.ModeloBanco;

public class F_PRINCIPAL extends javax.swing.JFrame { 
    Biblioteca          umabiblio            = new Biblioteca();
    GerarCopiaArquivo   gerarCopia            = new GerarCopiaArquivo();
    MetodosPublicos     umMetodo             = new MetodosPublicos();
    ConnConexao         conexao              = new ConnConexao();
    GetIPServidor       umIPServidor         = new GetIPServidor();
    ModeloBanco         modBanco             = new ModeloBanco();
    ControleGravarLog   umGravarLog          = new ControleGravarLog();
    String              data                 = new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis()));
    String              hora                 = new SimpleDateFormat("HH:mm:ss").format(new Date(System.currentTimeMillis())); //HH grava:ex:14hs se hh grava:02hs
   
    
    public F_PRINCIPAL()
    {
        initComponents();  
        setResizable(false);  //desabilitando o redimencionamento da tela
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); //desabilitando o botao fechar                
        
        //definição das propriedades 
        if(confIni){lblLogado.setText("SISTEMA : ADMINISTRADOR");}else{lblLogado.setText(umabiblio.mostrarNivelAcesso()+ " : " +nomeUsuario);}
        lblData.setText("Data : "+data);
        lblHora.setText("Hora : "+hora);
        lblNomeBanco.setText("BANCO : "+nomeBancoSetado+".FDB");
        lblNOMESERVIDOR.setText(umIPServidor.retornarNomeServidor());        
                
        lblDesenvolvido.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblLogado.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblData.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblHora.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblNomeBanco.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblNomeBanco.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        lblNOMESERVIDOR.setFont(new Font("TimesRoman",Font.BOLD,12)); 
        
        gerenciadorDeMenus();       
        
    }
    
    private void gerenciadorDeMenus(){        
       if(nivelAcessoUsuario >1)
       {
           mnuCONFIGURACOES.setVisible(false);
           mnuConsInformacoes.setVisible(false);
           menuReativacoes.setVisible(false);
           menutipodocumentos.setVisible(false);
           menugerarnumdocto.setVisible(false);           
       }      
    }
       
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblImagemPrincipal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogado = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblDesenvolvido = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblNomeBanco = new javax.swing.JLabel();
        lblNOMESERVIDOR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuTIPOS = new javax.swing.JMenuItem();
        menuSECOES = new javax.swing.JMenuItem();
        menuMODELOS = new javax.swing.JMenuItem();
        menuUSUARIOS = new javax.swing.JMenuItem();
        menuContatos = new javax.swing.JMenuItem();
        menuDepartamentos = new javax.swing.JMenuItem();
        menuCLIENTES = new javax.swing.JMenuItem();
        menuPatrimonios = new javax.swing.JMenuItem();
        menupatrimoniosmoveis = new javax.swing.JMenuItem();
        menuCadPatrimoniosEmLote = new javax.swing.JMenuItem();
        menutipodocumentos = new javax.swing.JMenuItem();
        menugerarnumdocto = new javax.swing.JMenuItem();
        menupatrideptos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuLogs = new javax.swing.JMenuItem();
        mnuCONSMONITORES = new javax.swing.JMenuItem();
        mnuCONSIMPRESSORAS = new javax.swing.JMenuItem();
        mnuConsInformacoes = new javax.swing.JMenuItem();
        mnuCONSIPSIMPRESSORAS = new javax.swing.JMenuItem();
        mnuCONSMICROS = new javax.swing.JMenuItem();
        mnuConsultarEstacoes = new javax.swing.JMenuItem();
        mnuConsultarEstacoesDisponiveis = new javax.swing.JMenuItem();
        menuEDICOES = new javax.swing.JMenu();
        menuEditarModeloPatrimonio = new javax.swing.JMenuItem();
        menuReativacoes = new javax.swing.JMenu();
        mnuReativarSecao = new javax.swing.JMenuItem();
        mnuReativarUsuario = new javax.swing.JMenuItem();
        mnuReativarPatrimonio = new javax.swing.JMenuItem();
        mnuReativarCliente = new javax.swing.JMenuItem();
        menuImpressoes = new javax.swing.JMenu();
        mnuEtiquetasIndividuais = new javax.swing.JMenuItem();
        mnuEtiquetasColetivas = new javax.swing.JMenuItem();
        mnuMemoTransferencia = new javax.swing.JMenuItem();
        mnuImprimirMemosTransferencia = new javax.swing.JMenuItem();
        mnuTarefas = new javax.swing.JMenu();
        mnuMEMORANDOS = new javax.swing.JMenu();
        mnuCONFIGURACOES = new javax.swing.JMenu();
        mnuIPServidor = new javax.swing.JMenuItem();
        mnuMudarBanco = new javax.swing.JMenuItem();
        mnuApoio = new javax.swing.JMenuItem();
        mnuDocumentacao = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        mnuLOGOFF = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA CONTROLE DE PATRIMÔNIOS DA PGM");

        jLayeredPane1.setBackground(new java.awt.Color(0, 204, 204));

        lblImagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGOMARCA.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogado.setText("Logado");

        lblHora.setText("Hora");

        lblDesenvolvido.setText("  Desenvolvido por Edi Aquino de Souza - Edsof");

        lblData.setText("Data");

        lblNomeBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeBanco.setText("nome do banco");

        lblNOMESERVIDOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNOMESERVIDOR.setText("ip do servidor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblDesenvolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNOMESERVIDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDesenvolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNOMESERVIDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(lblImagemPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(lblImagemPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(lblImagemPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_gravar.jpg"))); // NOI18N
        menuCadastro.setText("Cadastros");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuTIPOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuTIPOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_inicio.gif"))); // NOI18N
        menuTIPOS.setText("TIPOS");
        menuTIPOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTIPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTIPOSActionPerformed(evt);
            }
        });
        menuCadastro.add(menuTIPOS);

        menuSECOES.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSECOES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_calculadora.gif"))); // NOI18N
        menuSECOES.setText("SEÇÕES");
        menuSECOES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSECOES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSECOESActionPerformed(evt);
            }
        });
        menuCadastro.add(menuSECOES);

        menuMODELOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuMODELOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/building_add.png"))); // NOI18N
        menuMODELOS.setText("MODELOS");
        menuMODELOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMODELOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMODELOSActionPerformed(evt);
            }
        });
        menuCadastro.add(menuMODELOS);

        menuUSUARIOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuUSUARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users16.jpg"))); // NOI18N
        menuUSUARIOS.setText("USUÁRIOS");
        menuUSUARIOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUSUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUSUARIOSActionPerformed(evt);
            }
        });
        menuCadastro.add(menuUSUARIOS);

        menuContatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_professor.gif"))); // NOI18N
        menuContatos.setText("CONTATOS");
        menuContatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContatosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuContatos);

        menuDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_pesquisa.gif"))); // NOI18N
        menuDepartamentos.setText("DEPARTAMENTOS");
        menuDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartamentosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuDepartamentos);

        menuCLIENTES.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCLIENTES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Autor.gif"))); // NOI18N
        menuCLIENTES.setText("COLABORADORES");
        menuCLIENTES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCLIENTESActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCLIENTES);

        menuPatrimonios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPatrimonios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computador.png"))); // NOI18N
        menuPatrimonios.setText("PATRIMONIOS GERAL");
        menuPatrimonios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPatrimonios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatrimoniosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPatrimonios);

        menupatrimoniosmoveis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menupatrimoniosmoveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movel.png"))); // NOI18N
        menupatrimoniosmoveis.setText("PATRIMONIOS MOVEIS");
        menupatrimoniosmoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menupatrimoniosmoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupatrimoniosmoveisActionPerformed(evt);
            }
        });
        menuCadastro.add(menupatrimoniosmoveis);

        menuCadPatrimoniosEmLote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuCadPatrimoniosEmLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator_add.png"))); // NOI18N
        menuCadPatrimoniosEmLote.setText("PATRIMONIOS EM LOTE");
        menuCadPatrimoniosEmLote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadPatrimoniosEmLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadPatrimoniosEmLoteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadPatrimoniosEmLote);

        menutipodocumentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        menutipodocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        menutipodocumentos.setText("TIPO DE DOCUMENTOS");
        menutipodocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menutipodocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutipodocumentosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutipodocumentos);

        menugerarnumdocto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        menugerarnumdocto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Ok.gif"))); // NOI18N
        menugerarnumdocto.setText("GERAR NUMERO DOCUMENTOS");
        menugerarnumdocto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menugerarnumdocto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menugerarnumdoctoActionPerformed(evt);
            }
        });
        menuCadastro.add(menugerarnumdocto);

        menupatrideptos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menupatrideptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patrimonios.png"))); // NOI18N
        menupatrideptos.setText("PATRIMONIOS DEPARTAMENTOS");
        menupatrideptos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menupatrideptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupatrideptosActionPerformed(evt);
            }
        });
        menuCadastro.add(menupatrideptos);

        jMenuBar1.add(menuCadastro);

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_pesquisa.gif"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuLogs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blocoNotas.gif"))); // NOI18N
        menuLogs.setText("LOGS");
        menuLogs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogsActionPerformed(evt);
            }
        });
        menuConsultas.add(menuLogs);

        mnuCONSMONITORES.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuCONSMONITORES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monitor.png"))); // NOI18N
        mnuCONSMONITORES.setText("CONSULTA MONITORES");
        mnuCONSMONITORES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCONSMONITORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCONSMONITORESActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuCONSMONITORES);

        mnuCONSIMPRESSORAS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mnuCONSIMPRESSORAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_imprimir.gif"))); // NOI18N
        mnuCONSIMPRESSORAS.setText("CONSULTA IMPRESSORAS");
        mnuCONSIMPRESSORAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCONSIMPRESSORAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCONSIMPRESSORASActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuCONSIMPRESSORAS);

        mnuConsInformacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        mnuConsInformacoes.setText("CONSULTA INFORMAÇÕES");
        mnuConsInformacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuConsInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsInformacoesActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuConsInformacoes);

        mnuCONSIPSIMPRESSORAS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuCONSIPSIMPRESSORAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brick_add.png"))); // NOI18N
        mnuCONSIPSIMPRESSORAS.setText("CONSULTA IPS IMPRESSORAS");
        mnuCONSIPSIMPRESSORAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCONSIPSIMPRESSORAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCONSIPSIMPRESSORASActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuCONSIPSIMPRESSORAS);

        mnuCONSMICROS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuCONSMICROS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computador.png"))); // NOI18N
        mnuCONSMICROS.setText("CONSULTA ESTAÇÕES POR MODELO/SEÇÃO");
        mnuCONSMICROS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCONSMICROS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCONSMICROSActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuCONSMICROS);

        mnuConsultarEstacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultarEstacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patrimonios.png"))); // NOI18N
        mnuConsultarEstacoes.setText("CONSULTA ESTAÇÕES POR DEPARTAMENTO");
        mnuConsultarEstacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuConsultarEstacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarEstacoesActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuConsultarEstacoes);

        mnuConsultarEstacoesDisponiveis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultarEstacoesDisponiveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computador.png"))); // NOI18N
        mnuConsultarEstacoesDisponiveis.setText("NOMES DE ESTAÇÕES DISPONÍVEIS PARA CADASTRO");
        mnuConsultarEstacoesDisponiveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuConsultarEstacoesDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarEstacoesDisponiveisActionPerformed(evt);
            }
        });
        menuConsultas.add(mnuConsultarEstacoesDisponiveis);

        jMenuBar1.add(menuConsultas);

        menuEDICOES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/building_add.png"))); // NOI18N
        menuEDICOES.setText("Editar");
        menuEDICOES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuEditarModeloPatrimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TICK.PNG"))); // NOI18N
        menuEditarModeloPatrimonio.setText("Modelos Patrimônios");
        menuEditarModeloPatrimonio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuEditarModeloPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarModeloPatrimonioActionPerformed(evt);
            }
        });
        menuEDICOES.add(menuEditarModeloPatrimonio);

        jMenuBar1.add(menuEDICOES);

        menuReativacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Ok.gif"))); // NOI18N
        menuReativacoes.setText("Reativações");
        menuReativacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuReativarSecao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuReativarSecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_calculadora.gif"))); // NOI18N
        mnuReativarSecao.setText("SECOES");
        mnuReativarSecao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReativarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReativarSecaoActionPerformed(evt);
            }
        });
        menuReativacoes.add(mnuReativarSecao);

        mnuReativarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuReativarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users16.jpg"))); // NOI18N
        mnuReativarUsuario.setText("USUARIOS");
        mnuReativarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReativarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReativarUsuarioActionPerformed(evt);
            }
        });
        menuReativacoes.add(mnuReativarUsuario);

        mnuReativarPatrimonio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mnuReativarPatrimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/building_add.png"))); // NOI18N
        mnuReativarPatrimonio.setText("PATRIMOVEIS");
        mnuReativarPatrimonio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReativarPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReativarPatrimonioActionPerformed(evt);
            }
        });
        menuReativacoes.add(mnuReativarPatrimonio);

        mnuReativarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuReativarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_professor.gif"))); // NOI18N
        mnuReativarCliente.setText("COLABORADORES");
        mnuReativarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReativarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReativarClienteActionPerformed(evt);
            }
        });
        menuReativacoes.add(mnuReativarCliente);

        jMenuBar1.add(menuReativacoes);

        menuImpressoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_imprimir.gif"))); // NOI18N
        menuImpressoes.setText("Impressões");
        menuImpressoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuEtiquetasIndividuais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        mnuEtiquetasIndividuais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        mnuEtiquetasIndividuais.setText("Etiquetas Individuais");
        mnuEtiquetasIndividuais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuEtiquetasIndividuais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEtiquetasIndividuaisActionPerformed(evt);
            }
        });
        menuImpressoes.add(mnuEtiquetasIndividuais);

        mnuEtiquetasColetivas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mnuEtiquetasColetivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brick_add.png"))); // NOI18N
        mnuEtiquetasColetivas.setText("Etiquetas  Coletivas");
        mnuEtiquetasColetivas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuEtiquetasColetivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEtiquetasColetivasActionPerformed(evt);
            }
        });
        menuImpressoes.add(mnuEtiquetasColetivas);

        mnuMemoTransferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        mnuMemoTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blocoNotas.gif"))); // NOI18N
        mnuMemoTransferencia.setText("Gerar Memo Transferência");
        mnuMemoTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuMemoTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMemoTransferenciaActionPerformed(evt);
            }
        });
        menuImpressoes.add(mnuMemoTransferencia);

        mnuImprimirMemosTransferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        mnuImprimirMemosTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_imprimir.gif"))); // NOI18N
        mnuImprimirMemosTransferencia.setText("Listar Imprimir Memorandos");
        mnuImprimirMemosTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuImprimirMemosTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImprimirMemosTransferenciaActionPerformed(evt);
            }
        });
        menuImpressoes.add(mnuImprimirMemosTransferencia);

        jMenuBar1.add(menuImpressoes);

        mnuTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator_add.png"))); // NOI18N
        mnuTarefas.setText("Tarefas");
        mnuTarefas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuTarefasMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuTarefas);

        mnuMEMORANDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blocoNotas.gif"))); // NOI18N
        mnuMEMORANDOS.setText("Memorandos");
        mnuMEMORANDOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuMEMORANDOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMEMORANDOSMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuMEMORANDOS);

        mnuCONFIGURACOES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configs.png"))); // NOI18N
        mnuCONFIGURACOES.setText("Configurações");
        mnuCONFIGURACOES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuIPServidor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mnuIPServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patrimonios.png"))); // NOI18N
        mnuIPServidor.setText("IP Servidor");
        mnuIPServidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuIPServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIPServidorActionPerformed(evt);
            }
        });
        mnuCONFIGURACOES.add(mnuIPServidor);

        mnuMudarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mnuMudarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock_delete.png"))); // NOI18N
        mnuMudarBanco.setText("Setar Banco de Dados");
        mnuMudarBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuMudarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMudarBancoActionPerformed(evt);
            }
        });
        mnuCONFIGURACOES.add(mnuMudarBanco);

        mnuApoio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuApoio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Livro.gif"))); // NOI18N
        mnuApoio.setText("Formulario de Apoio");
        mnuApoio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuApoio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuApoioActionPerformed(evt);
            }
        });
        mnuCONFIGURACOES.add(mnuApoio);

        mnuDocumentacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuDocumentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TICK.PNG"))); // NOI18N
        mnuDocumentacao.setText("Documentação");
        mnuDocumentacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuDocumentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDocumentacaoActionPerformed(evt);
            }
        });
        mnuCONFIGURACOES.add(mnuDocumentacao);

        jMenuBar1.add(mnuCONFIGURACOES);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Pergunta.gif"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        mnuLOGOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users16.jpg"))); // NOI18N
        mnuLOGOFF.setText("Logoff");
        mnuLOGOFF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuLOGOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLOGOFFMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuLOGOFF);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_Ok.jpg"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        setSize(new java.awt.Dimension(1324, 889));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    

     
    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
             
             //copia no servidor
             if(!ipServidor.equals("LOCALHOST"))
             {
                gerarCopia.CopiarArquivo("\\\\10.71.32.55\\Meus Documentos\\Bancos_De_Projetos\\SysTarefas\\SYSTAREFAS.fdb", "\\\\10.71.32.55\\Meus Documentos\\Bancos_De_Projetos\\SysTarefas\\SYSDESENV.fdb");
             }else{
                //copia local
                gerarCopia.CopiarArquivo("C:\\Meus Documentos\\Bancos_De_Projetos\\SysTarefas\\SYSTAREFAS.fdb", "C:\\Meus Documentos\\Bancos_De_Projetos\\SysTarefas\\SYSDESENV.fdb");
             }
      
             umGravarLog.gravarLog("saida do Sistema"); 
              System.exit(0);
//         
//        if(umabiblio.ConfirmouOperacao("Tem certeza que deseja sair?", "Saindo do Sistema!")){
//            umGravarLog.gravarLog("saida do Sistema");
//            System.exit(0);
//        }
            
    }//GEN-LAST:event_menuSairMouseClicked

    private void mnuReativarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReativarClienteActionPerformed
        //Primeiro verifica se tem registros inativados, se positivo abre o formulario
        conexao.conectar();
        conexao.ExecutarPesquisaSQL("select * from tblclientes where status='INATIVO'");
        try {
            if (conexao.rs.next())
            {
                tabela = "TBLCLIENTES"; 
                status = "INATIVO";   //variavel determina que seja aberto o formulario somente com INATIVOS                
                F_REATIVARCLIENTES frm = new F_REATIVARCLIENTES();
                frm.setVisible(true); 
            }else{
                JOptionPane.showMessageDialog(null, "No momento não foram encontrados clientes inativados!");   
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "A consulta não pode ser executada, verifique!\nErro: " + ex.getMessage());            
        }finally{
             conexao.desconectar();
        }
    }//GEN-LAST:event_mnuReativarClienteActionPerformed

    private void mnuReativarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReativarSecaoActionPerformed
        tabela = "TBLSECOES";  
        F_REATIVARSECAO frm = new F_REATIVARSECAO();
        frm.setVisible(true);     
        
    }//GEN-LAST:event_mnuReativarSecaoActionPerformed

    private void mnuReativarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReativarUsuarioActionPerformed
        //Primeiro verifica se tem registros inativados, se positivo abre o formulario
        conexao.conectar();
        conexao.ExecutarPesquisaSQL("select * from tblusuarios where status='INATIVO'");
        try {
            if (conexao.rs.next())
            {
                tabela = "TBLUSUARIOS"; 
                status = "INATIVO";   //variavel determina que seja aberto o formulario somente com INATIVOS
                visualizandoInativos = true;
                F_REATIVARUSUARIOS frm = new F_REATIVARUSUARIOS();
                frm.setVisible(true); 
            }else{
                JOptionPane.showMessageDialog(null, "No momento não foram encontrados usuários inativados!");   
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "A consulta não pode ser executada, verifique!\nErro: " + ex.getMessage());            
        }finally{
             conexao.desconectar();
        }
         
    }//GEN-LAST:event_mnuReativarUsuarioActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        F_SOBRE frm = new F_SOBRE();
        frm.setVisible(true);  
    }//GEN-LAST:event_menuSobreMouseClicked

    private void mnuEtiquetasIndividuaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEtiquetasIndividuaisActionPerformed
        F_ETIQUETASIND frm = new F_ETIQUETASIND();
        frm.setVisible(true);  
    }//GEN-LAST:event_mnuEtiquetasIndividuaisActionPerformed

    private void mnuEtiquetasColetivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEtiquetasColetivasActionPerformed
        F_ETIQUETASCOL frm = new F_ETIQUETASCOL();
        frm.setVisible(true);  
    }//GEN-LAST:event_mnuEtiquetasColetivasActionPerformed

    private void mnuTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTarefasMouseClicked
        if(!umabiblio.tabelaVazia("tblclientes"))
        {
            tabela = "TBLTAREFAS";        
            F_TAREFAS frm = new F_TAREFAS();
            frm.setVisible(true); 
         }else{
            JOptionPane.showMessageDialog(null, "A tabela: tblclientes esta vazia cadastre clientes para continuar!");   
         }  
    }//GEN-LAST:event_mnuTarefasMouseClicked

    private void mnuMEMORANDOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMEMORANDOSMouseClicked
         
        tabela = "TBLMEMORANDOS";        
        F_MEMORANDOS frm = new F_MEMORANDOS();
        frm.setVisible(true); 
      
    }//GEN-LAST:event_mnuMEMORANDOSMouseClicked

    private void menuPatrimoniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatrimoniosActionPerformed
        if(!umabiblio.tabelaVazia("tblclientes"))
        {
            tabela = "TBLPATRIMONIOS";
            F_PATRIMONIOS frm = new F_PATRIMONIOS();
            frm.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "A tabela: tblsecoes e/ou tblclientes estão vazias cadastre seçoes e/ou clientes para continuar!");
        }
    }//GEN-LAST:event_menuPatrimoniosActionPerformed

    private void menuLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogsActionPerformed
        if(umabiblio.permissaoLiberada()){
            tabela = "TBLLOGS";
            F_LOGS frm = new F_LOGS();
            frm.setVisible(true);
            umGravarLog.gravarLog("acesso a consulta de logs");
        }
    }//GEN-LAST:event_menuLogsActionPerformed

    private void menuContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContatosActionPerformed
        tabela = "TBLCONTATOS";
        F_CONTATOS frm = new F_CONTATOS();
        frm.setVisible(true);
    }//GEN-LAST:event_menuContatosActionPerformed

    private void menuUSUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUSUARIOSActionPerformed
        tabela = "TBLUSUARIOS";
        status = "ATIVO";
        F_USUARIOS frm = new F_USUARIOS();
        frm.setVisible(true);
    }//GEN-LAST:event_menuUSUARIOSActionPerformed

    private void menuCLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCLIENTESActionPerformed
        tabela = "TBLCLIENTES";
        F_CLIENTES frm = new F_CLIENTES();
        frm.setVisible(true);
    }//GEN-LAST:event_menuCLIENTESActionPerformed

    private void menuSECOESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSECOESActionPerformed
        if(!umabiblio.tabelaVazia("TBLDEPARTAMENTOS"))
        {
            tabela = "TBLSECOES";
            status = "ATIVO";
            F_SECOES frm = new F_SECOES();
            frm.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "A tabela: tbldepartamentos esta vazia, primeiro cadastre departamentos para continuar!");
        }
    }//GEN-LAST:event_menuSECOESActionPerformed

    private void menuMODELOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMODELOSActionPerformed
        tabela = "TBLMODELOS";        
        F_MODELOS frm = new F_MODELOS();
        frm.setVisible(true); 
    }//GEN-LAST:event_menuMODELOSActionPerformed

    private void mnuCONSIMPRESSORASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCONSIMPRESSORASActionPerformed
        tabela = "TBLPATRIMONIOS";
        status = "ATIVO";
        F_CONSIMPRESSORAS frm = new F_CONSIMPRESSORAS();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCONSIMPRESSORASActionPerformed

    private void mnuCONSMICROSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCONSMICROSActionPerformed
        tabela = "TBLPATRIMONIOS";
        status = "ATIVO";
        F_CONSMICROS frm = new F_CONSMICROS();
        frm.setVisible(true);  
    }//GEN-LAST:event_mnuCONSMICROSActionPerformed

    private void mnuCONSMONITORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCONSMONITORESActionPerformed
        tabela = "TBLPATRIMONIOS";
        status = "ATIVO";
        F_CONSMONITORES frm = new F_CONSMONITORES();
        frm.setVisible(true);  
    }//GEN-LAST:event_mnuCONSMONITORESActionPerformed

    private void mnuIPServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIPServidorActionPerformed
        F_CONFIGURACOES frm = new F_CONFIGURACOES();
        frm.setVisible(true);  
    }//GEN-LAST:event_mnuIPServidorActionPerformed

    private void menuTIPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTIPOSActionPerformed
        tabela = "TBLTIPOS";
        status = "ATIVO";
        F_TIPOS frm = new F_TIPOS();
        frm.setVisible(true);  
    }//GEN-LAST:event_menuTIPOSActionPerformed

    private void mnuCONSIPSIMPRESSORASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCONSIPSIMPRESSORASActionPerformed
        tabela = "TBLIPSDISPONIVEIS";
        F_CONSIPSDISPONIVEIS frm = new F_CONSIPSDISPONIVEIS();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCONSIPSIMPRESSORASActionPerformed

    private void menuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartamentosActionPerformed
        tabela = "TBLDEPARTAMENTOS";
        status = "ATIVO";
        F_DEPARTAMENTOS frm = new F_DEPARTAMENTOS();
        frm.setVisible(true);  
    }//GEN-LAST:event_menuDepartamentosActionPerformed

    private void menuEditarModeloPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarModeloPatrimonioActionPerformed
     if(umabiblio.permissaoLiberada()){    
        tabela = "TBLPATRIMONIOS";
        status = "ATIVO";
        F_EDITARMODELOS frm = new F_EDITARMODELOS();
        frm.setVisible(true);  
     }
    }//GEN-LAST:event_menuEditarModeloPatrimonioActionPerformed

    private void menupatrimoniosmoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupatrimoniosmoveisActionPerformed
        tabela = "TBLPATRIMOVEL";
        status = "ATIVO";
        F_PATRIMOMOVEL frm = new F_PATRIMOMOVEL();
        frm.setVisible(true);  
    }//GEN-LAST:event_menupatrimoniosmoveisActionPerformed

    private void mnuReativarPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReativarPatrimonioActionPerformed
        //Primeiro verifica se tem registros inativados, se positivo abre o formulario
        conexao.conectar();
        conexao.ExecutarPesquisaSQL("select * from tblpatrimovel where status='INATIVO'");
        try {
            if (conexao.rs.next())
            {
                tabela = "TBLPATRIMOVEL"; 
                status = "INATIVO";   //variavel determina que seja aberto o formulario somente com INATIVOS                
                F_REATIVARPATRIMOVEL frm = new F_REATIVARPATRIMOVEL();
                frm.setVisible(true); 
            }else{
                JOptionPane.showMessageDialog(null, "No momento não foram encontrados patrimônios inativados!");   
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "A consulta não pode ser executada, verifique!\nErro: " + ex.getMessage());            
        }finally{
             conexao.desconectar();
        }
    }//GEN-LAST:event_mnuReativarPatrimonioActionPerformed

    private void mnuConsInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsInformacoesActionPerformed
        //Primeiro verifica se tem registros na tabela de tipos de documentos, se positivo abre o formulario
        conexao.conectar();
        conexao.ExecutarPesquisaSQL("select * from tblusuarios where rf='D631863'");
        try {
            if (conexao.rs.next())
            {
                if(rfUsuario.equals(conexao.rs.getString("rf"))){                
                    tabela = "TBLINFORMACOES";        
                    F_ACESSOS frm = new F_ACESSOS();
                    frm.setVisible(true); 
                }else{   
                    JOptionPane.showMessageDialog(null, "Atenção você não tem permissão para este tipo de acesso!", "Sem permissão de acesso!", 2);
                }
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "A consulta não pode ser executada, verifique!\nErro: " + ex.getMessage());            
        }finally{
             conexao.desconectar();
        }
   
    }//GEN-LAST:event_mnuConsInformacoesActionPerformed

    private void menutipodocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutipodocumentosActionPerformed
        if(umabiblio.permissaoLiberada()){    
            tabela = "TBLTIPODOCUMENTOS";  
            F_TIPODOCUMENTO frm = new F_TIPODOCUMENTO();
            frm.setVisible(true);   
        }
    }//GEN-LAST:event_menutipodocumentosActionPerformed

    private void menugerarnumdoctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menugerarnumdoctoActionPerformed
        //Primeiro verifica se tem registros na tabela de tipos de documentos, se positivo abre o formulario
        
        conexao.conectar();
        conexao.ExecutarPesquisaSQL("select * from tbltipodocumentos where status='ATIVO'");
        try {
            if (conexao.rs.next())
            {
                tabela = "TBLDESPACHOS";  
                F_DESPACHOS frm = new F_DESPACHOS(this,true);
                frm.setVisible(true);  
            }else{
                JOptionPane.showMessageDialog(null, "Atenção cadastre primeiro os tipos de documentos!");   
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "A consulta não pode ser executada, verifique!\nErro: " + ex.getMessage());            
        }finally{
             conexao.desconectar();
        } 
        
        //JOptionPane.showMessageDialog(null, "Atenção este módulo esta em desenvolvimento!","Módulo em Desenvolvimento!",2); 
    }//GEN-LAST:event_menugerarnumdoctoActionPerformed
    
    private void mnuMudarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMudarBancoActionPerformed
        //Setar banco de dados    
        F_SETARBANCO frm = new F_SETARBANCO(this,true);
        frm.setVisible(true); 
        
        if(alterouBanco){
            lblNomeBanco.setText("BANCO : "+nomeBancoSetado+".FDB");   
        }
        
    }//GEN-LAST:event_mnuMudarBancoActionPerformed

    private void mnuMemoTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMemoTransferenciaActionPerformed
        //chama F_LISTAOPCOES PARA DEFINIR INICIALMENTE QUAL TABELA SERA UTILIZADA PATRIMONIOS DA CGGM OU PATRIMONIOS DOS DEPTOS        
        tabela = "TBLITENSMEMOTRANSFERIDOS";   
        F_MEMOITENSTRANSFERIDOS frm = new F_MEMOITENSTRANSFERIDOS();
        frm.setVisible(true);             
    }//GEN-LAST:event_mnuMemoTransferenciaActionPerformed

    private void mnuConsultarEstacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarEstacoesActionPerformed
        
        F_ESTACOES frm = new F_ESTACOES();
        frm.setVisible(true); 
        
    }//GEN-LAST:event_mnuConsultarEstacoesActionPerformed

    private void mnuApoioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuApoioActionPerformed
        if(umabiblio.permissaoLiberada()){  
            F_APOIO frm = new F_APOIO(new javax.swing.JFrame(), true);
            frm.setVisible(true);  
        }
    }//GEN-LAST:event_mnuApoioActionPerformed

    private void mnuConsultarEstacoesDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarEstacoesDisponiveisActionPerformed
        
        F_CONSNOMESTACOESDISPONIVEIS frm = new F_CONSNOMESTACOESDISPONIVEIS();
        frm.setVisible(true); 
        
    }//GEN-LAST:event_mnuConsultarEstacoesDisponiveisActionPerformed

    private void mnuLOGOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLOGOFFMouseClicked
        F_LOGIN frm = new F_LOGIN();
        frm.setVisible(true); 
        dispose();
    }//GEN-LAST:event_mnuLOGOFFMouseClicked

    private void mnuDocumentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDocumentacaoActionPerformed
        tabela = "TBLDOCUMENTACAO";        
        F_DOCUMENTACAO frm = new F_DOCUMENTACAO();
        frm.setVisible(true); 
    }//GEN-LAST:event_mnuDocumentacaoActionPerformed

    private void mnuImprimirMemosTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImprimirMemosTransferenciaActionPerformed
        if(!umabiblio.tabelaVazia("TBLMEMOSTRANSFERIDOS"))
        {                   
            F_LISTAMEMOSTRANSFERIDOS frm = new F_LISTAMEMOSTRANSFERIDOS(); 
            frm.setVisible(true); 
         }else{
            JOptionPane.showMessageDialog(null, "A tabela de memorandos esta vazia acesse o menu (Impressões->Gerar Memo Transferência) e cadastre o primerio memorando para continuar!","Tabela vazia",2);  
            
         }  
    }//GEN-LAST:event_mnuImprimirMemosTransferenciaActionPerformed

    private void menupatrideptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupatrideptosActionPerformed
        tabela = "TBLPATRIDEPTOS";     
        F_PATRIDEPTOS frm = new F_PATRIDEPTOS(); 
        frm.setVisible(true); 
    }//GEN-LAST:event_menupatrideptosActionPerformed

    private void menuCadPatrimoniosEmLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadPatrimoniosEmLoteActionPerformed

        if(umMetodo.ConfirmouOperacao("Atenção, tenha  em  mente que para gerar o arquivo TXT e cadastrar os equipamentos em lote é necessário ter o \nMODELO dos mesmos cadastrados. Você  já  cadastrou os modelos dos equipamentos  para  prosseguimento?", "Cadastro de equipamentos em lote"))
        {
             F_CADPATRIMONIOSVIATXT frm = new F_CADPATRIMONIOSVIATXT();
             frm.setVisible(true);       
        }else{
            //abre tela para cadastro de modelos
            tabela = "TBLMODELOS";        
            F_MODELOS frm = new F_MODELOS();
            frm.setVisible(true); 
        }
        
    }//GEN-LAST:event_menuCadPatrimoniosEmLoteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(F_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(F_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(F_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(F_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                 new F_PRINCIPAL().setVisible(true);
////                
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDesenvolvido;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblImagemPrincipal;
    private javax.swing.JLabel lblLogado;
    public javax.swing.JLabel lblNOMESERVIDOR;
    public javax.swing.JLabel lblNomeBanco;
    private javax.swing.JMenuItem menuCLIENTES;
    private javax.swing.JMenuItem menuCadPatrimoniosEmLote;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuContatos;
    private javax.swing.JMenuItem menuDepartamentos;
    private javax.swing.JMenu menuEDICOES;
    private javax.swing.JMenuItem menuEditarModeloPatrimonio;
    private javax.swing.JMenu menuImpressoes;
    private javax.swing.JMenuItem menuLogs;
    private javax.swing.JMenuItem menuMODELOS;
    private javax.swing.JMenuItem menuPatrimonios;
    private javax.swing.JMenu menuReativacoes;
    private javax.swing.JMenuItem menuSECOES;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem menuTIPOS;
    private javax.swing.JMenuItem menuUSUARIOS;
    private javax.swing.JMenuItem menugerarnumdocto;
    private javax.swing.JMenuItem menupatrideptos;
    private javax.swing.JMenuItem menupatrimoniosmoveis;
    private javax.swing.JMenuItem menutipodocumentos;
    private javax.swing.JMenuItem mnuApoio;
    private javax.swing.JMenu mnuCONFIGURACOES;
    private javax.swing.JMenuItem mnuCONSIMPRESSORAS;
    private javax.swing.JMenuItem mnuCONSIPSIMPRESSORAS;
    private javax.swing.JMenuItem mnuCONSMICROS;
    private javax.swing.JMenuItem mnuCONSMONITORES;
    private javax.swing.JMenuItem mnuConsInformacoes;
    private javax.swing.JMenuItem mnuConsultarEstacoes;
    private javax.swing.JMenuItem mnuConsultarEstacoesDisponiveis;
    private javax.swing.JMenuItem mnuDocumentacao;
    private javax.swing.JMenuItem mnuEtiquetasColetivas;
    private javax.swing.JMenuItem mnuEtiquetasIndividuais;
    private javax.swing.JMenuItem mnuIPServidor;
    private javax.swing.JMenuItem mnuImprimirMemosTransferencia;
    private javax.swing.JMenu mnuLOGOFF;
    private javax.swing.JMenu mnuMEMORANDOS;
    private javax.swing.JMenuItem mnuMemoTransferencia;
    private javax.swing.JMenuItem mnuMudarBanco;
    private javax.swing.JMenuItem mnuReativarCliente;
    private javax.swing.JMenuItem mnuReativarPatrimonio;
    private javax.swing.JMenuItem mnuReativarSecao;
    private javax.swing.JMenuItem mnuReativarUsuario;
    private javax.swing.JMenu mnuTarefas;
    // End of variables declaration//GEN-END:variables
}
